#!/bin/bash

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
SRC_DIR="$(cd -P "$(dirname "$SCRIPTS_DIR")" && pwd)"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Reformat Python code inline using ruff.
"
}

if [ "${1:-}" = "--help" ]; then
    usage
else
    echo "Running ruff format ..."
    pushd $SRC_DIR >/dev/null
    ruff format rastervision_*/ tests/ integration_tests/ docs/conf.py ruff.toml
    popd >/dev/null
fi
